dist: trusty
language: python
sudo: true

addons:
   apt:
      packages:
      - libatlas3gf-base
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - python-scipy

python:
  - 3.6

env:
  matrix:
    # This environment tests for python 3 packages with conda
    - DISTRIB="conda" PYTHON_VERSION="3.6"
      NUMPY_VERSION="1.13.3" XLWT_VERSION="1.3.0" XLRD_VERSION="1.1.0"
      COVERAGE="true"
#    # This environment tests for python 3.9 packages with conda
#    - DISTRIB="conda_min" PYTHON_VERSION="3.9"
#      NUMPY_VERSION="1.13.3" XLWT_VERSION="1.3.0" XLRD_VERSION="1.1.0"
#      COVERAGE="true"
    # basic Ubuntu build environment
    - DISTRIB="ubuntu" PYTHON_VERSION="3.6" INSTALL_ATLAS="true"
      NUMPY_VERSION="1.13.3" XLWT_VERSION="1.3.0" XLRD_VERSION="1.1.0"
      COVERAGE="true"

install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache: apt
